#!/usr/bin/env python3
"""Build stock-news.js: the 뉴스·영상 tab's "종목 소식" column (2026-10-08 user decision).

The column gathers the dated items already on each card's "시계열 주요 뉴스" timeline and
lists them newest first. It adds nothing a card does not already say - no new events, no
summaries - so the tab and the cards cannot disagree. It reads this repo's cards/ (the
copies that are live), so run it after sync_cards.py in the promotion order.

Each item keeps the card's own heading text, category dot, title and source link. The
reaction % is recomputed from the card's DAILY the way the card's own script does it
(scripts/extract_card_timelines.js), never copied from the HTML.

Dates: the heading starts with the announcement date ("2026년 8월 26일 발표 · 8월 27일 반응 —
..."). A few headings give only a month or a span ("2026년 5월 —", "2025년 11월 3~18일 —");
those sort under their first stated day, or the reaction day, or the 1st of the month.

Usage: python3 scripts/build_stock_news.py [--check]
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "stock-news.js"
FULL = re.compile(r"^(\d{4})년 (\d{1,2})월 (\d{1,2})일")
MONTH = re.compile(r"^(\d{4})년 (\d{1,2})(?:~\d{1,2})?월")


def names():
    rows = {}
    for line in (REPO / "stock-data.js").read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith('{"rank"'):
            r = json.JSONDecoder().raw_decode(line)[0]
            rows[r["ticker"]] = r["name"]
    return rows


def item_date(item):
    m = FULL.match(item["heading"])
    if m:
        return f"{int(m[1]):04d}-{int(m[2]):02d}-{int(m[3]):02d}", False
    m = MONTH.match(item["heading"])
    if not m:
        raise SystemExit(f"timeline heading without a date: {item['heading']!r}")
    first = re.match(r"^\d{4}년 \d{1,2}월 (\d{1,2})~", item["heading"])
    if first:
        return f"{int(m[1]):04d}-{int(m[2]):02d}-{int(first[1]):02d}", True
    if item.get("reactDate", "") and item["reactDate"][:7] == f"{int(m[1]):04d}-{int(m[2]):02d}":
        return item["reactDate"], True
    return f"{int(m[1]):04d}-{int(m[2]):02d}-01", True


def build():
    out = subprocess.run(["node", str(REPO / "scripts/extract_card_timelines.js")],
                         capture_output=True, text=True, check=True).stdout
    cards = json.loads(out)
    bad = sorted(t for t, v in cards.items() if "error" in v)
    if bad:
        raise SystemExit(f"timeline extraction failed for: {', '.join(bad)}")
    name = names()
    items = []
    for t, v in cards.items():
        for it in v["items"]:
            d, approx = item_date(it)
            items.append({"date": d, "approx": approx, "ticker": t, "name": name.get(t, t),
                          "category": it["category"], "heading": it["heading"], "title": it["title"],
                          "url": it["url"], "source": it["source"], "reaction": it["reaction"], "trend": it["trend"],
                          "href": f"cards/{t}_full_widget.html"})
    items.sort(key=lambda x: (x["date"], x["ticker"]), reverse=True)
    meta = re.search(r'"asOf":\s*"([\d-]+)"', (REPO / "stock-data.js").read_text(encoding="utf-8"))
    data = {"asOf": meta[1] if meta else None, "items": items}
    return ("// Generated by scripts/build_stock_news.py from cards/ timelines. Do not edit.\n"
            "window.StockNews=" + json.dumps(data, ensure_ascii=False) + ";\n"), len(items)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    text, n = build()
    if a.check:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print("STALE - stock-news.js does not match cards/")
            sys.exit(1)
        print(f"OK - stock-news.js matches cards/ ({n} items)")
        return
    OUT.write_text(text, encoding="utf-8")
    print(f"Wrote {OUT} ({n} items)")


if __name__ == "__main__":
    main()
